services:
  - type: web
    name: savedieties-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_URL
        value: https://savedieties1.onrender.com
      - key: FRONTEND_URL
        value: https://savedeitiesma.netlify.app
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false